version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: root
      POSTGRES_DB: MessagingApp
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge